source 'https://rubygems.org'

gem 'scraperwiki', git: 'https://github.com/openaustralia/scraperwiki-ruby.git', branch: 'morph_defaults'
gem 'wikidata-fetcher', git: 'https://github.com/everypolitician/wikidata-fetcher.git'
gem 'colorize'
gem 'mediawiki_api'
gem 'nokogiri'
gem 'open-uri-cached'
gem 'pry'
gem 'rest-client'
